### ISSUE TITLE
Adventures with windows

### ISSUE THREAD

**Issue by joheli** [adamkewley/jobson-ui#21]
I do realize that Windows is not supported and I am only pursuing this avenue as there is no other os available at my workplace.

Despite the bad odds I got in an adventureous mood yesterday and started jobson 1.0.0 on a Windows Server 2012 R2, using a slightly altered Batch file named `jobson.bat` containing the single line `java -jar ..\share\java\jobson-1.0.0.jar %*`. 

That bit worked.

Unfortunately, when I tried to load jobson-ui by putting the contents of directory `share/jobson/ui/html` into a fresh directory served by nginx 1.14.0 I only got a brief message in a browser saying, `Loading Jobson (libraries, data, etc.)...` without having had the ui rendered. Btw. I used the same nginx configuration as in the [example](https://github.com/adamkewley/jobson-ui/blob/master/docs/nginx-example-config).

I have not found any specific error message in nginx's `error.log` or `access.log`. 

Is there another error output I could use? I have to admit that I don't have the faintest idea about node js.

Thank you for any hint!

**Comment by adamkewley** [comment]
Hi,

I'm amazed you got that far =).

That message you're seeing is the bootstrap message that appears in the HTML ([source](https://github.com/adamkewley/jobson/blob/master/jobson-ui/src/html/index.html)) before the Javascript has loaded.

Based on what you've said, I imagine the error is that the browser you're using is having an issue loading `jobson-ui`'s Javascript. Previous versions of `jobson-ui` compiled the assets using `babel` to make them backwards-compatible with ~IE10, but the current `jobson-ui` is assuming a modern browser (it uses ES6). 

What browser are you testing with?

**Comment by adamkewley** [comment]
@joheli was it a browser thing?

**Comment by adamkewley** [comment]
I am closing this issue because this project has been merged into the `jobson` project as part of the `1.0.0` release. The UI will now be implemented in that project, not here. Please consult the project page:

https://github.com/adamkewley/jobson
